package easywebflow.sample.model;
// Generated 2012-01-01 22:49:53 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="CATEGORIES"
    ,catalog="INZ_SKLEP"
)
public class Category  implements java.io.Serializable {


     private int idCategory;
     private String name;
     private Set<CategoryFeature> categoryFeatures = new HashSet<CategoryFeature>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(int idCategory, String name) {
        this.idCategory = idCategory;
        this.name = name;
    }
    public Category(int idCategory, String name, Set<CategoryFeature> categoryFeatures, Set<Product> products) {
       this.idCategory = idCategory;
       this.name = name;
       this.categoryFeatures = categoryFeatures;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="idCategory", unique=true, nullable=false)
    public int getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<CategoryFeature> getCategoryFeatures() {
        return this.categoryFeatures;
    }
    
    public void setCategoryFeatures(Set<CategoryFeature> categoryFeatures) {
        this.categoryFeatures = categoryFeatures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


