package easywebflow.sample.model;
// Generated 2012-01-13 09:00:41 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoryFeature generated by hbm2java
 */
@Entity
@Table(name="CATEGORY_FEATURES"
    ,catalog="INZ_SKLEP"
)
public class CategoryFeature  implements java.io.Serializable {


     private CategoryFeatureId id;
     private Feature feature;
     private Category category;
     private Set<FeatureValue> featureValues = new HashSet<FeatureValue>(0);

    public CategoryFeature() {
    }

	
    public CategoryFeature(CategoryFeatureId id, Feature feature, Category category) {
        this.id = id;
        this.feature = feature;
        this.category = category;
    }
    public CategoryFeature(CategoryFeatureId id, Feature feature, Category category, Set<FeatureValue> featureValues) {
       this.id = id;
       this.feature = feature;
       this.category = category;
       this.featureValues = featureValues;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="catIdCategory", column=@Column(name="CAT_idCategory", nullable=false) ), 
        @AttributeOverride(name="featIdFeature", column=@Column(name="FEAT_idFeature", nullable=false) ) } )
    public CategoryFeatureId getId() {
        return this.id;
    }
    
    public void setId(CategoryFeatureId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FEAT_idFeature", nullable=false, insertable=false, updatable=false)
    public Feature getFeature() {
        return this.feature;
    }
    
    public void setFeature(Feature feature) {
        this.feature = feature;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CAT_idCategory", nullable=false, insertable=false, updatable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="categoryFeature")
    public Set<FeatureValue> getFeatureValues() {
        return this.featureValues;
    }
    
    public void setFeatureValues(Set<FeatureValue> featureValues) {
        this.featureValues = featureValues;
    }




}


