package easywebflow.sample.model;
// Generated 2012-01-13 09:00:41 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feature generated by hbm2java
 */
@Entity
@Table(name="FEATURES"
    ,catalog="INZ_SKLEP"
)
public class Feature  implements java.io.Serializable {


     private Integer idFeature;
     private String name;
     private Set<CategoryFeature> categoryFeatures = new HashSet<CategoryFeature>(0);

    public Feature() {
    }

	
    public Feature(String name) {
        this.name = name;
    }
    public Feature(String name, Set<CategoryFeature> categoryFeatures) {
       this.name = name;
       this.categoryFeatures = categoryFeatures;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFeature", unique=true, nullable=false)
    public Integer getIdFeature() {
        return this.idFeature;
    }
    
    public void setIdFeature(Integer idFeature) {
        this.idFeature = idFeature;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="feature")
    public Set<CategoryFeature> getCategoryFeatures() {
        return this.categoryFeatures;
    }
    
    public void setCategoryFeatures(Set<CategoryFeature> categoryFeatures) {
        this.categoryFeatures = categoryFeatures;
    }




}


