package easywebflow.sample.model;
// Generated 2012-01-01 22:49:53 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feature generated by hbm2java
 */
@Entity
@Table(name="FEATURES"
    ,catalog="INZ_SKLEP"
)
public class Feature  implements java.io.Serializable {


     private int idCategoryFeature;
     private String name;
     private Set<CategoryFeature> categoryFeatures = new HashSet<CategoryFeature>(0);

    public Feature() {
    }

	
    public Feature(int idCategoryFeature, String name) {
        this.idCategoryFeature = idCategoryFeature;
        this.name = name;
    }
    public Feature(int idCategoryFeature, String name, Set<CategoryFeature> categoryFeatures) {
       this.idCategoryFeature = idCategoryFeature;
       this.name = name;
       this.categoryFeatures = categoryFeatures;
    }
   
     @Id 

    
    @Column(name="idCategoryFeature", unique=true, nullable=false)
    public int getIdCategoryFeature() {
        return this.idCategoryFeature;
    }
    
    public void setIdCategoryFeature(int idCategoryFeature) {
        this.idCategoryFeature = idCategoryFeature;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="feature")
    public Set<CategoryFeature> getCategoryFeatures() {
        return this.categoryFeatures;
    }
    
    public void setCategoryFeatures(Set<CategoryFeature> categoryFeatures) {
        this.categoryFeatures = categoryFeatures;
    }




}


