package easywebflow.sample.model;
// Generated 2012-01-01 22:49:53 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="ORDERS"
    ,catalog="INZ_SKLEP"
)
public class Order  implements java.io.Serializable {


     private int idOrder;
     private User user;
     private String receiverName;
     private String receiverAddress;
     private Date date;
     private String receiverName2;
     private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

    public Order() {
    }

	
    public Order(int idOrder, User user, String receiverName, String receiverAddress, Date date) {
        this.idOrder = idOrder;
        this.user = user;
        this.receiverName = receiverName;
        this.receiverAddress = receiverAddress;
        this.date = date;
    }
    public Order(int idOrder, User user, String receiverName, String receiverAddress, Date date, String receiverName2, Set<OrderItem> orderItems) {
       this.idOrder = idOrder;
       this.user = user;
       this.receiverName = receiverName;
       this.receiverAddress = receiverAddress;
       this.date = date;
       this.receiverName2 = receiverName2;
       this.orderItems = orderItems;
    }
   
     @Id 

    
    @Column(name="idORDER", unique=true, nullable=false)
    public int getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(int idOrder) {
        this.idOrder = idOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERS_idUSER", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="RECEIVER_NAME", nullable=false, length=45)
    public String getReceiverName() {
        return this.receiverName;
    }
    
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    
    @Column(name="RECEIVER_ADDRESS", nullable=false, length=45)
    public String getReceiverAddress() {
        return this.receiverAddress;
    }
    
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="RECEIVER_NAME2", length=45)
    public String getReceiverName2() {
        return this.receiverName2;
    }
    
    public void setReceiverName2(String receiverName2) {
        this.receiverName2 = receiverName2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderItem> getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }




}


