package easywebflow.sample.model;
// Generated 2012-01-13 09:00:41 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.inject.Named;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 * Modified by adding @Named
 */
@Entity
@Table(name="ORDERS"
    ,catalog="INZ_SKLEP"
)
@Named
public class Order  implements java.io.Serializable {


     private Integer idOrder;
     private ShipmentType shipmentType;
     private PaymentType paymentType;
     private User user;
     private String receiverName;
     private String receiverAddress;
     private Date date;
     private BigDecimal totalValue;
     private String receiverName2;
     private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

    public Order() {
    }

	
    public Order(ShipmentType shipmentType, PaymentType paymentType, User user, String receiverName, String receiverAddress, Date date, BigDecimal totalValue) {
        this.shipmentType = shipmentType;
        this.paymentType = paymentType;
        this.user = user;
        this.receiverName = receiverName;
        this.receiverAddress = receiverAddress;
        this.date = date;
        this.totalValue = totalValue;
    }
    public Order(ShipmentType shipmentType, PaymentType paymentType, User user, String receiverName, String receiverAddress, Date date, BigDecimal totalValue, String receiverName2, Set<OrderItem> orderItems) {
       this.shipmentType = shipmentType;
       this.paymentType = paymentType;
       this.user = user;
       this.receiverName = receiverName;
       this.receiverAddress = receiverAddress;
       this.date = date;
       this.totalValue = totalValue;
       this.receiverName2 = receiverName2;
       this.orderItems = orderItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idORDER", unique=true, nullable=false)
    public Integer getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(Integer idOrder) {
        this.idOrder = idOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SHIP_idSHIPMENT", nullable=false)
    public ShipmentType getShipmentType() {
        return this.shipmentType;
    }
    
    public void setShipmentType(ShipmentType shipmentType) {
        this.shipmentType = shipmentType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAY_idPAYMENT", nullable=false)
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERS_idUSER", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="receiver_name", length=45)
    public String getReceiverName() {
        return this.receiverName;
    }
    
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    
    @Column(name="receiver_address", length=45)
    public String getReceiverAddress() {
        return this.receiverAddress;
    }
    
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="total_value", nullable=false, precision=8)
    public BigDecimal getTotalValue() {
        return this.totalValue;
    }
    
    public void setTotalValue(BigDecimal totalValue) {
        this.totalValue = totalValue;
    }

    
    @Column(name="receiver_name2", length=45)
    public String getReceiverName2() {
        return this.receiverName2;
    }
    
    public void setReceiverName2(String receiverName2) {
        this.receiverName2 = receiverName2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderItem> getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }




}


