package easywebflow.sample.model;
// Generated 2012-01-01 22:49:53 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderItemId generated by hbm2java
 */
@Embeddable
public class OrderItemId  implements java.io.Serializable {


     private int ordIdOrder;
     private int prodIdProduct;

    public OrderItemId() {
    }

    public OrderItemId(int ordIdOrder, int prodIdProduct) {
       this.ordIdOrder = ordIdOrder;
       this.prodIdProduct = prodIdProduct;
    }
   


    @Column(name="ORD_idORDER", nullable=false)
    public int getOrdIdOrder() {
        return this.ordIdOrder;
    }
    
    public void setOrdIdOrder(int ordIdOrder) {
        this.ordIdOrder = ordIdOrder;
    }


    @Column(name="PROD_idPRODUCT", nullable=false)
    public int getProdIdProduct() {
        return this.prodIdProduct;
    }
    
    public void setProdIdProduct(int prodIdProduct) {
        this.prodIdProduct = prodIdProduct;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderItemId) ) return false;
		 OrderItemId castOther = ( OrderItemId ) other; 
         
		 return (this.getOrdIdOrder()==castOther.getOrdIdOrder())
 && (this.getProdIdProduct()==castOther.getProdIdProduct());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrdIdOrder();
         result = 37 * result + this.getProdIdProduct();
         return result;
   }   


}


