package easywebflow.sample.model;
// Generated 2012-01-13 09:00:41 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name="PAYMENT_TYPES"
,catalog="INZ_SKLEP"
		)
@NamedQuery(name=PaymentType.FIND_ALL, query="select s from PaymentType s")  
public class PaymentType  implements java.io.Serializable {

	public static final String FIND_ALL = "Payment.findAll";   

	private int idPayment;
	private String name;
	private Set<Order> orders = new HashSet<Order>(0);

	public PaymentType() {
	}


	public PaymentType(int idPayment, String name) {
		this.idPayment = idPayment;
		this.name = name;
	}
	public PaymentType(int idPayment, String name, Set<Order> orders) {
		this.idPayment = idPayment;
		this.name = name;
		this.orders = orders;
	}

	@Id 


	@Column(name="idPAYMENT", unique=true, nullable=false)
	public int getIdPayment() {
		return this.idPayment;
	}

	public void setIdPayment(int idPayment) {
		this.idPayment = idPayment;
	}


	@Column(name="name", nullable=false, length=45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="paymentType")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}




}


