package easywebflow.sample.model;
// Generated 2012-01-13 09:00:41 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShipmentType generated by hbm2java
 * Modified added NamedQuery
 */
@Entity
@Table(name="SHIPMENT_TYPES"
,catalog="INZ_SKLEP"
		)
@NamedQuery(name=ShipmentType.FIND_ALL, query="select s from ShipmentType s")    
public class ShipmentType  implements java.io.Serializable {

	public static final String FIND_ALL = "Shipment.findAll";    

	private int idShipment;
	private String name;
	private BigDecimal price;
	private Set<Order> orders = new HashSet<Order>(0);

	public ShipmentType() {
	}


	public ShipmentType(int idShipment, String name, BigDecimal price) {
		this.idShipment = idShipment;
		this.name = name;
		this.price = price;
	}
	public ShipmentType(int idShipment, String name, BigDecimal price, Set<Order> orders) {
		this.idShipment = idShipment;
		this.name = name;
		this.price = price;
		this.orders = orders;
	}

	@Id 


	@Column(name="idSHIPMENT", unique=true, nullable=false)
	public int getIdShipment() {
		return this.idShipment;
	}

	public void setIdShipment(int idShipment) {
		this.idShipment = idShipment;
	}


	@Column(name="name", nullable=false, length=45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	@Column(name="price", nullable=false, precision=4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="shipmentType")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}




}


