package easywebflow.sample.model;
// Generated 2012-01-01 22:49:53 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,catalog="INZ_SKLEP"
    , uniqueConstraints = @UniqueConstraint(columnNames="login") 
)
@NamedQuery(name=User.FIND_BY_LOGIN, query="select u from User u where u.login = :login")
public class User implements java.io.Serializable {

	public static final String FIND_BY_LOGIN = "User.findUserByLogin";
	
     private int idUser;
     private String login;
     private String password;
     private String name;
     private String address;
     private String name2;
     private Set<Order> orders = new HashSet<Order>(0);

    public User() {
    }

	
    public User(int idUser, String login, String password, String name, String address) {
        this.idUser = idUser;
        this.login = login;
        this.password = password;
        this.name = name;
        this.address = address;
    }
    public User(int idUser, String login, String password, String name, String address, String name2, Set<Order> orders) {
       this.idUser = idUser;
       this.login = login;
       this.password = password;
       this.name = name;
       this.address = address;
       this.name2 = name2;
       this.orders = orders;
    }
   
     @Id 

    
    @Column(name="idUSER", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="login", unique=true, nullable=false, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address", nullable=false, length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="name2", length=45)
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


