package easywebflow.sample.model;
// Generated 2012-01-25 23:17:58 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserGroupId generated by hbm2java
 */
@Embeddable
public class UserGroupId  implements java.io.Serializable {


     private int usersIdUser;
     private int groupsIdGroup;

    public UserGroupId() {
    }

    public UserGroupId(int usersIdUser, int groupsIdGroup) {
       this.usersIdUser = usersIdUser;
       this.groupsIdGroup = groupsIdGroup;
    }
   


    @Column(name="USERS_idUSER", nullable=false)
    public int getUsersIdUser() {
        return this.usersIdUser;
    }
    
    public void setUsersIdUser(int usersIdUser) {
        this.usersIdUser = usersIdUser;
    }


    @Column(name="GROUPS_idGROUP", nullable=false)
    public int getGroupsIdGroup() {
        return this.groupsIdGroup;
    }
    
    public void setGroupsIdGroup(int groupsIdGroup) {
        this.groupsIdGroup = groupsIdGroup;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserGroupId) ) return false;
		 UserGroupId castOther = ( UserGroupId ) other; 
         
		 return (this.getUsersIdUser()==castOther.getUsersIdUser())
 && (this.getGroupsIdGroup()==castOther.getGroupsIdGroup());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsersIdUser();
         result = 37 * result + this.getGroupsIdGroup();
         return result;
   }   


}


